language: objective-c
matrix:
  include:
    - osx_image: xcode7.3
    - osx_image: xcode8
install:
  - gem install cocoapods -v 1.1.1
script:
  - pod lib lint
  - xcodebuild -scheme 'BMSAnalyticsAPI iOS' clean build CODE_SIGN_IDENTITY= CODE_SIGNING_REQUIRED=NO
  - xcodebuild -scheme 'BMSAnalyticsAPI watchOS' clean build CODE_SIGN_IDENTITY= CODE_SIGNING_REQUIRED=NO
  - xcodebuild test -scheme 'BMSAnalyticsAPI Tests' -destination 'platform=iOS Simulator,name=iPhone 6s'

  # When merging to the master branch, we check if the version specified in the .podspec does not already exist as a git tag.
  # If the version does not exist yet, we add a git tag for this new version and publish to Cocoapods.
  - if [ "${TRAVIS_PULL_REQUEST}" = "false" ] && [ "${TRAVIS_BRANCH}" = "master" ] && [[ "${TRAVIS_JOB_NUMBER}" = *".2"* ]]; then
        cd ~/Documents;
        git clone https://ibm-bluemix-mobile-services:${GITHUB_TOKEN}@github.com/ibm-bluemix-mobile-services/bms-clientsdk-swift-analytics-api.git;
        cd bms-clientsdk-swift-analytics-api;
        git remote rm origin;
        git remote add origin https://ibm-bluemix-mobile-services:${GITHUB_TOKEN}@github.com/ibm-bluemix-mobile-services/bms-clientsdk-swift-analytics-api.git;
        version=$(grep -o 'version.*=.*[0-9]' BMSAnalyticsAPI.podspec | cut -f 2 -d "'");
        git fetch --tags;
        git_tags=$(git tag);
        if [[ ! " ${array[@]} " =~ " ${version} " ]]; then
          echo "Publishing new version ${version} ";
          git tag $version;
          git push origin --tags;
          pod trunk push;
        fi
      fi