language: objective-c
matrix:
  include:
    - osx_image: xcode7.3
    - osx_image: xcode8.1
install:
  - gem install jazzy
before_script:
  # This seems to reduce random build failures
  - mkdir -p /Users/travis/Library/Developer/CoreSimulator/Devices/5752202B-E7A2-4B6C-9D7B-B211C2F54654/data/Documents
  - chmod -R 777 /Users/travis/Library/Developer/CoreSimulator
  - rm -rf ~/Library/Developer/Xcode/DerivedData
script:
  # Test that the framework can be installed and built, and passes all unit tests
  - travis_wait pod update
  - carthage update
  - pod lib lint
  - xcodebuild -scheme 'BMSAnalytics iOS' clean build CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO
  - xcodebuild -scheme 'BMSAnalytics watchOS' clean build CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO
  - travis_retry xcodebuild test -scheme 'BMSAnalytics Tests' -destination 'platform=iOS Simulator,name=iPhone 6s' CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO

  # When merging or pushing to the master branch, release a new version and publish the API documentation
  - if [ "${TRAVIS_PULL_REQUEST}" = "false" ] && [ "${TRAVIS_BRANCH}" = "master" ] && [[ "${TRAVIS_JOB_NUMBER}" = *".2"* ]]; then
      bash scripts/release.sh;
      bash scripts/publish-docs.sh;
    fi